# -*- coding: utf-8 -*-
"""krishnaveni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nBsfA-1fbLwgvDxDeuYbcpbuCFq_vUH
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd

orders = pd.read_csv("orders.csv")
orders.head()

users = pd.read_json("users.json")
users.head()

import sqlite3

conn = sqlite3.connect("food_delivery.db")

cursor = conn.cursor()

with open("restaurants.sql", "r") as file:
    sql_script = file.read()

cursor.executescript(sql_script)
conn.commit()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

import pandas as pd

restaurants = pd.read_sql_query("SELECT * FROM restaurants", conn)
restaurants.head()

conn.close()

import sqlite3

conn = sqlite3.connect("food.db")
cursor = conn.cursor()

with open("restaurants.sql", "r") as f:
    sql_script = f.read()

cursor.executescript(sql_script)
conn.commit()

restaurants = pd.read_sql_query("SELECT * FROM restaurants", conn)
restaurants.head()

final_df = orders.merge(users, on="user_id", how="left")

final_df = final_df.merge(restaurants, on="restaurant_id", how="left")

final_df.to_csv("final_food_delivery_dataset.csv", index=False)

files.download("final_food_delivery_dataset.csv")

final_df.info()
final_df.describe()
final_df.head()

gold_revenue_city = (
    final_df[final_df['membership'] == 'Gold']
    .groupby('city')['total_amount']
    .sum()
    .sort_values(ascending=False)
)

gold_revenue_city

avg_order_cuisine = (
    final_df.groupby('cuisine')['total_amount']
    .mean()
    .sort_values(ascending=False)
)

avg_order_cuisine

user_spend = final_df.groupby('user_id')['total_amount'].sum()

users_above_1000 = user_spend[user_spend > 1000].count()

users_above_1000

bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['3.0–3.5', '3.6–4.0', '4.1–4.5', '4.6–5.0']

final_df['rating_range'] = pd.cut(final_df['rating'], bins=bins, labels=labels)

rating_revenue = final_df.groupby('rating_range')['total_amount'].sum().sort_values(ascending=False)

rating_revenue

gold_df = final_df[final_df['membership'] == 'Gold']

avg_order_gold_city = (
    gold_df.groupby('city')['total_amount']
    .mean()
    .sort_values(ascending=False)
)

avg_order_gold_city

restaurant_count = final_df.groupby('cuisine')['restaurant_id'].nunique()

cuisine_revenue = final_df.groupby('cuisine')['total_amount'].sum()

cuisine_summary = pd.DataFrame({
    'restaurant_count': restaurant_count,
    'total_revenue': cuisine_revenue
}).sort_values(by='restaurant_count')

cuisine_summary

# Total orders
total_orders = final_df['order_id'].nunique()

# Gold member orders
gold_orders = final_df[final_df['membership'] == 'Gold']['order_id'].nunique()

# Percentage
gold_percentage = round((gold_orders / total_orders) * 100)
gold_percentage

restaurant_stats = (
    final_df.groupby('restaurant_id')
    .agg(
        avg_order_value=('total_amount', 'mean'),
        total_orders=('order_id', 'count')
    )
)

# Filter restaurants with less than 20 orders
filtered_restaurants = restaurant_stats[restaurant_stats['total_orders'] < 20]

# Sort by highest average order value
top_restaurant = filtered_restaurants.sort_values(
    by='avg_order_value', ascending=False
).head(1)

top_restaurant

combo_revenue = (
    final_df
    .groupby(['membership', 'cuisine'])['total_amount']
    .sum()
    .sort_values(ascending=False)
)

combo_revenue.head(1)

final_df['order_date'] = pd.to_datetime(final_df['order_date'])

final_df['quarter'] = final_df['order_date'].dt.quarter

quarter_revenue = (
    final_df
    .groupby('quarter')['total_amount']
    .sum()
    .sort_values(ascending=False)
)

quarter_revenue

quarter_revenue.index = quarter_revenue.index.map({
    1: 'Q1 (Jan–Mar)',
    2: 'Q2 (Apr–Jun)',
    3: 'Q3 (Jul–Sep)',
    4: 'Q4 (Oct–Dec)'
})

quarter_revenue

gold_orders = final_df[final_df['membership'] == 'Gold'].shape[0]
gold_orders

hyderabad_revenue = final_df[final_df['city'] == 'Hyderabad']['total_amount'].sum()
round(hyderabad_revenue)

distinct_users = final_df['user_id'].nunique()
distinct_users

gold_avg_order_value = final_df[final_df['membership'] == 'Gold']['total_amount'].mean()
round(gold_avg_order_value, 2)

high_rating_orders = final_df[final_df['rating'] >= 4.5].shape[0]
high_rating_orders

top_city_gold = (
    final_df[final_df['membership'] == 'Gold']
    .groupby('city')['total_amount']
    .sum()
    .sort_values(ascending=False)
    .index[0]
)

top_city_gold

orders_top_city_gold = final_df[
    (final_df['membership'] == 'Gold') &
    (final_df['city'] == top_city_gold)
].shape[0]

orders_top_city_gold

